### note:以下代码均在jupyter notebook环境下运行 

In [2]:
from __future__ import print_function
import torch

### Construct a 5x3 matrix, uninitialized:

In [4]:
x = torch.empty(5, 3)
x

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.4013e-45,  4.1988e+07,  3.0357e+32],
        [ 1.8077e-43,  0.0000e+00, -9.8977e+14],
        [ 4.5587e-41, -9.8977e+14,  4.5587e-41],
        [ 1.9421e+20,  1.2689e+31,  3.2745e-12]])

### Construct a randomly initialized matrix:

In [6]:
x = torch.rand(5, 3)
x

tensor([[0.9046, 0.9585, 0.9514],
        [0.0378, 0.1977, 0.3705],
        [0.9859, 0.6566, 0.4674],
        [0.4531, 0.0799, 0.0832],
        [0.7482, 0.0206, 0.0081]])

### Construct a matrix filled zeros and of dtype long:

In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

### Construct a tensor directly from data:

In [9]:
x = torch.tensor([5, 5.6])
x

tensor([5.0000, 5.6000])

###  create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [10]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [17]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.2819,  0.2288, -0.9526],
        [ 0.3936, -0.3623,  1.0637],
        [ 1.2500, -0.2002, -1.7437],
        [-1.5013,  1.2681, -2.3494],
        [ 1.2887, -1.4394, -1.3454]])

### Get its size:

In [18]:
x.size() #torch.Size is in fact a tuple, so it supports all tuple operations.

torch.Size([5, 3])

### add operations have four method implement

In [24]:
y = torch.rand(5, 3)
x + y 

tensor([[ 0.2860,  0.9478, -0.3545],
        [ 0.9185,  0.5565,  1.0682],
        [ 1.6724,  0.5511, -1.6873],
        [-0.7344,  1.5276, -1.3511],
        [ 1.4060, -0.8836, -1.0592]])

In [21]:
torch.add(x, y)

tensor([[ 0.9842,  0.4418, -0.6129],
        [ 0.5656,  0.2233,  1.9036],
        [ 1.4750,  0.2356, -1.4260],
        [-1.1853,  2.2448, -2.1061],
        [ 1.9475, -1.0793, -0.6328]])

In [22]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 0.9842,  0.4418, -0.6129],
        [ 0.5656,  0.2233,  1.9036],
        [ 1.4750,  0.2356, -1.4260],
        [-1.1853,  2.2448, -2.1061],
        [ 1.9475, -1.0793, -0.6328]])

In [25]:
y

tensor([[0.0041, 0.7190, 0.5981],
        [0.5248, 0.9187, 0.0046],
        [0.4224, 0.7513, 0.0564],
        [0.7670, 0.2596, 0.9984],
        [0.1173, 0.5557, 0.2862]])

In [23]:
y.add_(x) #改变了y的值
y

tensor([[ 0.9842,  0.4418, -0.6129],
        [ 0.5656,  0.2233,  1.9036],
        [ 1.4750,  0.2356, -1.4260],
        [-1.1853,  2.2448, -2.1061],
        [ 1.9475, -1.0793, -0.6328]])

### 可以像numpy一样进行索引

In [27]:
x

tensor([[ 0.2819,  0.2288, -0.9526],
        [ 0.3936, -0.3623,  1.0637],
        [ 1.2500, -0.2002, -1.7437],
        [-1.5013,  1.2681, -2.3494],
        [ 1.2887, -1.4394, -1.3454]])

In [26]:
x[:, 1]

tensor([ 0.2288, -0.3623, -0.2002,  1.2681, -1.4394])

### resize/reshpe 张量可以使用torch.view函数

In [39]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [41]:
x,y

(tensor([[-1.0750,  0.2496, -1.2126,  0.3299],
         [-1.4994,  0.8969, -0.4225, -1.0557],
         [ 1.0600,  0.1811, -0.6309,  0.0643],
         [-0.1317, -0.3522,  0.3918, -0.1294]]),
 tensor([-1.0750,  0.2496, -1.2126,  0.3299, -1.4994,  0.8969, -0.4225, -1.0557,
          1.0600,  0.1811, -0.6309,  0.0643, -0.1317, -0.3522,  0.3918, -0.1294]))

In [42]:
x,z

(tensor([[-1.0750,  0.2496, -1.2126,  0.3299],
         [-1.4994,  0.8969, -0.4225, -1.0557],
         [ 1.0600,  0.1811, -0.6309,  0.0643],
         [-0.1317, -0.3522,  0.3918, -0.1294]]),
 tensor([[-1.0750,  0.2496, -1.2126,  0.3299, -1.4994,  0.8969, -0.4225, -1.0557],
         [ 1.0600,  0.1811, -0.6309,  0.0643, -0.1317, -0.3522,  0.3918, -0.1294]]))

In [45]:
x

tensor([[-1.0750,  0.2496, -1.2126,  0.3299],
        [-1.4994,  0.8969, -0.4225, -1.0557],
        [ 1.0600,  0.1811, -0.6309,  0.0643],
        [-0.1317, -0.3522,  0.3918, -0.1294]])

In [43]:
z = x.view(-1,2)
z

tensor([[-1.0750,  0.2496],
        [-1.2126,  0.3299],
        [-1.4994,  0.8969],
        [-0.4225, -1.0557],
        [ 1.0600,  0.1811],
        [-0.6309,  0.0643],
        [-0.1317, -0.3522],
        [ 0.3918, -0.1294]])

### 如果张量只有一个元素,那么可使用.item()可以获得实际的值

In [56]:
x = torch.randn(1)
x

tensor([-1.4161])

In [57]:
x.item()

-1.416090965270996

### numpy与torch tensor互相转换

#### torch tensor转换为numpy

In [61]:
a = torch.ones(4)
a

tensor([1., 1., 1., 1.])

In [60]:
b = a.numpy()
b

array([1., 1., 1., 1.], dtype=float32)

#### numpy转换为torch tensor

In [62]:
import numpy as np
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [63]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

### tensors可以使用.to方法移到任何设备上

In [68]:
if torch.cuda.is_available():
    print("我有GPU")

我有GPU


In [69]:
x

tensor([-1.4161])

In [81]:
import time
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)#y直接创建张量在GPU上
    x = x.to(device)
    start = time.time()
    z = x + y
    end = time.time()
    print(z)
    print(end-start)
    #print(z.to("cpu", torch.double))
    

tensor([-0.4161], device='cuda:0')
0.00032711029052734375


In [86]:
import time
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)#y直接创建张量在GPU上
    x = x.to(device)
    start = time.time()
    z = x + y
    end = time.time()
    print(z.to("cpu", torch.double))
    print(end-start)
    

tensor([-0.4161], dtype=torch.float64)
0.0009472370147705078
